In [1]:
#Quais pacientes precisar√£o da UTI?

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
import pandas as pd

In [13]:
df = pd.read_excel('/content/drive/MyDrive/Estudos/Bootcamp_DS/Arquivos/Kaggle_Sirio_Libanes_ICU_Prediction.xlsx')

In [14]:
df.head()

   PATIENT_VISIT_IDENTIFIER  AGE_ABOVE65  ...    WINDOW  ICU
0                         0            1  ...       0-2    0
1                         0            1  ...       2-4    0
2                         0            1  ...       4-6    0
3                         0            1  ...      6-12    0
4                         0            1  ...  ABOVE_12    1

[5 rows x 231 columns]